// <auto-generated />
using System;
using ExpenseTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExpenseTracker.Migrations
{
    [DbContext(typeof(ExpenseDbContext))]
    partial class ExpenseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExpenseTracker.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 125.50m,
                            Category = 0,
                            CreatedAt = new DateTime(2026, 2, 12, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5273),
                            Date = new DateTime(2026, 2, 12, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5268),
                            Description = "Weekly groceries from supermarket",
                            Title = "Grocery Shopping"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 45.00m,
                            Category = 1,
                            CreatedAt = new DateTime(2026, 2, 13, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5278),
                            Date = new DateTime(2026, 2, 13, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5278),
                            Description = "Fuel for car",
                            Title = "Gas Station"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1200.00m,
                            Category = 2,
                            CreatedAt = new DateTime(2026, 2, 14, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5282),
                            Date = new DateTime(2026, 2, 14, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5281),
                            Description = "Apartment rent for December",
                            Title = "Monthly Rent"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 85.30m,
                            Category = 3,
                            CreatedAt = new DateTime(2026, 2, 15, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5284),
                            Date = new DateTime(2026, 2, 15, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5284),
                            Description = "Monthly electricity payment",
                            Title = "Electricity Bill"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 32.00m,
                            Category = 4,
                            CreatedAt = new DateTime(2026, 2, 16, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5287),
                            Date = new DateTime(2026, 2, 16, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5287),
                            Description = "Cinema tickets for 2",
                            Title = "Movie Tickets"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 150.00m,
                            Category = 5,
                            CreatedAt = new DateTime(2026, 2, 10, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5291),
                            Date = new DateTime(2026, 2, 10, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5291),
                            Description = "General checkup",
                            Title = "Doctor Visit"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 89.99m,
                            Category = 6,
                            CreatedAt = new DateTime(2026, 2, 11, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5294),
                            Date = new DateTime(2026, 2, 11, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5294),
                            Description = "Running shoes from sports store",
                            Title = "New Shoes"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 49.99m,
                            Category = 7,
                            CreatedAt = new DateTime(2026, 2, 7, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5297),
                            Date = new DateTime(2026, 2, 7, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5296),
                            Description = "Programming course subscription",
                            Title = "Online Course"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 320.00m,
                            Category = 8,
                            CreatedAt = new DateTime(2026, 2, 2, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5300),
                            Date = new DateTime(2026, 2, 2, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5299),
                            Description = "Weekend getaway",
                            Title = "Hotel Stay"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 5.50m,
                            Category = 0,
                            CreatedAt = new DateTime(2026, 2, 17, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5303),
                            Date = new DateTime(2026, 2, 17, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5303),
                            Description = "Morning coffee",
                            Title = "Coffee Shop"
                        },
                        new
                        {
                            Id = 11,
                            Amount = 12.50m,
                            Category = 1,
                            CreatedAt = new DateTime(2026, 2, 9, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5306),
                            Date = new DateTime(2026, 2, 9, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5305),
                            Description = "Ride to office",
                            Title = "Uber Ride"
                        },
                        new
                        {
                            Id = 12,
                            Amount = 59.99m,
                            Category = 3,
                            CreatedAt = new DateTime(2026, 2, 8, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5309),
                            Date = new DateTime(2026, 2, 8, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5308),
                            Description = "Monthly internet service",
                            Title = "Internet Bill"
                        },
                        new
                        {
                            Id = 13,
                            Amount = 75.00m,
                            Category = 4,
                            CreatedAt = new DateTime(2026, 2, 5, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5311),
                            Date = new DateTime(2026, 2, 5, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5311),
                            Description = "Live music event",
                            Title = "Concert Tickets"
                        },
                        new
                        {
                            Id = 14,
                            Amount = 28.50m,
                            Category = 5,
                            CreatedAt = new DateTime(2026, 2, 6, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5314),
                            Date = new DateTime(2026, 2, 6, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5313),
                            Description = "Prescription medicines",
                            Title = "Pharmacy"
                        },
                        new
                        {
                            Id = 15,
                            Amount = 129.99m,
                            Category = 6,
                            CreatedAt = new DateTime(2026, 2, 4, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5317),
                            Date = new DateTime(2026, 2, 4, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5316),
                            Description = "New winter jacket",
                            Title = "Clothing Store"
                        },
                        new
                        {
                            Id = 16,
                            Amount = 65.00m,
                            Category = 7,
                            CreatedAt = new DateTime(2026, 2, 3, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5320),
                            Date = new DateTime(2026, 2, 3, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5319),
                            Description = "Educational textbooks",
                            Title = "Book Purchase"
                        },
                        new
                        {
                            Id = 17,
                            Amount = 450.00m,
                            Category = 8,
                            CreatedAt = new DateTime(2026, 1, 28, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5323),
                            Date = new DateTime(2026, 1, 28, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5322),
                            Description = "Business trip",
                            Title = "Flight Ticket"
                        },
                        new
                        {
                            Id = 18,
                            Amount = 95.00m,
                            Category = 0,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5326),
                            Date = new DateTime(2026, 1, 30, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5326),
                            Description = "Family dinner",
                            Title = "Restaurant Dinner"
                        },
                        new
                        {
                            Id = 19,
                            Amount = 8.00m,
                            Category = 1,
                            CreatedAt = new DateTime(2026, 2, 1, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5329),
                            Date = new DateTime(2026, 2, 1, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5329),
                            Description = "Mall parking",
                            Title = "Parking Fee"
                        },
                        new
                        {
                            Id = 20,
                            Amount = 35.00m,
                            Category = 3,
                            CreatedAt = new DateTime(2026, 1, 31, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5332),
                            Date = new DateTime(2026, 1, 31, 10, 56, 40, 950, DateTimeKind.Utc).AddTicks(5331),
                            Description = "Monthly water service",
                            Title = "Water Bill"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
